server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?usessl=false&serverTimezone=UTC
    username: root
    password: gaki
  devtools:
    restart:
      enabled: true


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.emory.springcloud.entity
